kind: pipeline
name: default

steps:
  - name: yarn
    image: node:10.16
    commands:
      - node -v
      - npm -v
      - yarn config set cache-folder .yarn-cache
      - yarn --version
      - yarn install
      - yarn prod

  - name: composer
    image: curder/laravel-docker
    commands:
      - php -v
      - composer -V
      - composer install --prefer-dist -vvv

  - name: rsync
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
      PLUGIN_TARGET:
        from_secret: rsync_target
    settings:
      hosts:
        - dev.webfsd.com
      source: ./*
      include:
        - "**.*"
      exclude:
        - "**.*"
      script:
        - cd ${PLUGIN_TARGET} && ls -la
